language: rust
rust:
- stable
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt
- rustup component add rustfmt
script:
- cargo fmt --all -- --check
- cargo build