language: rust
rust:
- stable
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt
- rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
script:
- cargo fmt -- --write-mode=diff
- cargo build